---
- name: Installing Docker with python packages
  hosts: all
  remote_user: ubuntu
  sudo: yes
  vars:
    - update_apt_cache: yes

  tasks:
   - name: Install pip
     apt: name=python-pip update_cache={{ update_apt_cache }} state=present

   - name: Upgrade pip
     pip: name=pip state=latest
     tags: packages

   - name: Install addition(required) python packages using PIP
     pip: name={{ item }} state=latest
     with_items:
       - boto3
       - docker-compose
       - awscli

   - name: Add the Docker public GPG key to the apt repo
     apt_key: url=https://download.docker.com/linux/ubuntu/gpg
              state=present

   - name: Add the Docker repo to the trusted sources list
     apt_repository: repo='deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
                     update_cache={{ update_apt_cache }}
                     state=present

   - name: Install Docker
     apt: name=docker state=installed