---
- name: Install packages and dependencies
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=installed
  with_items:
    - default-jdk
    - libfontconfig
    - libffi-dev
    - libncurses5-dev

- name: Add the Jenkins public GPG key to the apt repo
  apt_key: url=https://pkg.jenkins.io/debian/jenkins-ci.org.key
           state=present

- name: Add Jenkins to the trusted sources list
  apt_repository: repo='http://pkg.jenkins.io/debian-stable binary/'
                  update_cache={{ update_apt_cache }}
                  state=present

- name: Install Jenkins server
  apt: name=jenkins state=installed
  
- name: start jenkins
  systemd:
    name: jenkins
    state: started

- name: enable jenkins
  systemd:
    name: jenkins
    enabled: true
    
- name: sleep for 30 seconds and continue with play
  wait_for: timeout=30
  delegate_to: localhost

- name: initial jenkins password checking
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: result

- name: print init password jenkins
  debug:
    var: result.stdout