---
 - hosts:
     - << IP >>
   gather_facts: no
   tasks:
     - name: install web server
       yum: name=httpd state=present
#       apt: name-apache2 state=present
       tags: install
     - name: install index page
       copy: src=/root/index.html dest=/var/www/html/index.html backup=yes
       tags: configure
       notify: restart httpd
   handlers:
     - name: restart httpd
       service: name=httpd state=restarted
#       service: name=apache2 state=restarted

 - hosts:
     - local
   gather_facts: no
   tasks:
     - name: install mysql server
       yum: name=mysql-server state=present
